version: 2.1
orbs:
  docker: circleci/docker@2.1.2
jobs:
  build-docker-image:
      executor:
        name: docker/docker
        tag: "3.6"
      steps:
        - checkout
        - docker/install-docker-tools
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Build  and push Docker image
            command: |
              docker build -t containeregistrytest.azurecr.io/docker-dotnet-api:latest .
              docker login -u containeregistrytest -p 8u8MO/3GJImih+1RKRdhgtIzPVtavoSU9pN0Ex/f+e+ACRBIcywu containeregistrytest.azurecr.io
              docker push containeregistrytest.azurecr.io/docker-dotnet-api:latest
workflows:
  build-and-deploy:
    jobs:
      - build-docker-image